# kubernetes/apps/traefik/overlays/dev/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-dev
namespace: traefik
resources:
  - ../../base   # IngressRoute, Middleware, etc.
patchesStrategicMerge:
  - ingressroute-patch.yaml

configMapGenerator: # NEW
  - name: traefik-env-values
    literals:
      - traefik-lb-ip=192.168.10.170 # Example IP for dev

replacements: # NEW
  - source:
      kind: ConfigMap
      name: traefik-env-values
      fieldPath: data.traefik-lb-ip
    targets:
      - select:
          kind: HelmRelease # Assuming Kustomize transforms HelmChart to HelmRelease or similar
          name: traefik
        fieldPaths:
          - spec.values.service.annotations.metallb.universe.tf/loadBalancerIPs
