# kubernetes/apps/traefik/overlays/dev/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-dev

namespace: traefik

resources:
  - ../../base       # contiendra uniquement des CR supplémentaires (IngressRoute...)

configMapGenerator:
  - name: traefik-values
    files:
      - values-patch.yaml
generatorOptions:
  disableNameSuffixHash: true