# kubernetes/apps/metallb/base/ipaddresspools.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool-cluster
  namespace: metallb-system
spec:
  addresses:
    - _IP_RANGE_DEFAULT_
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: service-pool-cluster
  namespace: metallb-system
spec:
  addresses:
    - _IP_RANGE_SERVICE_
  autoAssign: false
