# kubernetes/apps/metallb/base/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - namespace.yaml
  - metallb-crds.yaml
  - metallb.yaml
  - rbac.yaml
commonLabels:
  app.kubernetes.io/part-of: metallb
  app.kubernetes.io/version: v0.15.2
images:
  - name: quay.io/metallb/controller
    newTag: v0.15.2
  - name: quay.io/metallb/speaker
    newTag: v0.15.2