# kubernetes/apps/metallb/base/metallb.yaml
---
# Manifest upstream v0.15.2 (non modifié) – livré via URL externe
# https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml
# Kustomize le récupère grâce à « resources: https://… »
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml