apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool-cluster
  namespace: metallb-system
spec:
  addresses:
  - 192.168.208.240-192.168.208.249
  autoAssign: true
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: service-pool-cluster
  namespace: metallb-system
spec:
  addresses:
  - 192.168.208.70-192.168.208.79
  autoAssign: false
  avoidBuggyIPs: true