apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml

patches:
  - path: ipaddresspools.yaml
  - path: l2advertisement.yaml

labels:
  - pairs:
      environment: dev
      cluster: vixens-dev
    includeSelectors: true