# kubernetes/apps/metallb/overlays/dev/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
bases:
  - ../../base
patchesStrategicMerge:
  - ipaddresspool-default.yaml
  - ipaddresspool-service.yaml
  - l2advertisement.yaml
configMapGenerator:
  - name: metallb-dev-overlays
    options:
      disableNameSuffixHash: true
    literals:
      - env=dev