# kubernetes/apps/metallb/overlays/dev/speaker-tolerations.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  template:
    spec:
      tolerations:
        # Déjà présent dans le manifest upstream, on les garde
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule