# apps-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            # on ne prend QUE le secret du cluster local
            # on va y ajouter le label "env" juste après
  template:
    metadata:
      name: '{{name}}-{{metadata.labels.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/<org>/<repo>
        targetRevision: '{{metadata.labels.env}}'  # 👈 branche dynamique
        path: apps/overlays/{{metadata.labels.env}}
      destination:
        name: '{{name}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true