apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: in-cluster
            server: https://kubernetes.default.svc
            env: dev
            project: default
          - name: in-cluster
            server: https://kubernetes.default.svc
            env: staging
            project: default
          - name: in-cluster
            server: https://kubernetes.default.svc
            env: main
            project: default
  selector:
    matchLabels:
      env: '{{.env}}'
  template:
    metadata:
      name: 'argocd-{{.env}}'
    spec:
      project: '{{.project}}'
      source:
        repoURL: https://github.com/charchess/vixens-new
        targetRevision: '{{.env}}'
        path: 'kubernetes/overlays/argocd/{{.env}}'
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true