apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true              # ➜ interpolation Go-template
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  selector:
    matchLabels:
      env: ""                   # seulement les clusters labelisés env
  template:
    metadata:
      name: 'argocd-{{.metadata.labels.env}}'   # ➜ valeur résolue
    spec:
      project: default
      source:
        repoURL: https://github.com/charchess/vixens-new
        targetRevision: '{{.metadata.labels.env}}'
        path: 'kubernetes/overlays/argocd/{{.metadata.labels.env}}'
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true