# kubernetes/apps/traefik.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 37.2.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/values-base.yaml
          - $values/values-patch.yaml
    - repoURL: https://github.com/charchess/vixens-new
      targetRevision: HEAD
      ref: values
      path: kubernetes/apps/traefik   # <-- dossier contenant les 2 values
  path: overlays/dev                # Kustomize appliqué après
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true