# kubernetes/apps/traefik.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/charchess/vixens-new
    targetRevision: HEAD
    path: kubernetes/apps/traefik/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  #  ➜  autorise Kustomize à utiliser helmCharts
  plugin:
    name: kustomize
    env:
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /home/argocd/.kustomize/plugin
      - name: HELM_PLUGINS
        value: /home/argocd/.helm/plugins
    args:
      - --enable-helm