apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vixens-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/charchess/vixens-new
    targetRevision: dev   # ou la branche de ton repo App-of-Apps
    path: kubernetes/  # dossier qui contient l’ApplicationSet argocd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true