variable "cluster_endpoint" {
  type        = string
  description = "API endpoint (https://vip:6443) used to reach cluster API"
}

variable "controlplane_yaml_path" {
  type        = string
  description = "Path to the global controlplane.yaml generated by talosctl gen config"
}

variable "talos_certs" {
  description = "Talos client certificates (base64 or PEM). Must match Talos API credentials."
  type = object({
    ca   = string
    cert = string
    key  = string
  })
}

variable "controlplanes" {
  description = "Map of controlplane nodes to configure"
  type = map(object({
    ip           = string
    hostname     = string
    install_disk = string
    patch_path   = string
  }))
}

variable "argocd_lb_ip" {
  description = "IP statique pour le service LoadBalancer d’ArgoCD (laisser vide pour DHCP)"
  type        = string
  default     = ""
}