variable "argocd_lb_ip" {
  description = "IP statique pour le service LoadBalancer d’ArgoCD (laisser vide pour DHCP)"
  type        = string
  default     = ""
}

variable "cluster_endpoint" {
  type        = string
  description = "API endpoint (https://vip:6443) used to reach cluster API"

  validation {
    condition     = can(regex("^https://[^:]+:[0-9]+$", var.cluster_endpoint))
    error_message = "Cluster endpoint must be in format https://host:port"
  }
}

variable "controlplanes" {
  description = "Map of controlplane nodes to configure"
  type = map(object({
    ip           = string
    hostname     = string
    install_disk = string
    patch_path   = string
  }))

  validation {
    condition = alltrue([
      for node in var.controlplanes :
      can(regex("^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$", node.ip))
    ])
    error_message = "All node IPs must be valid IPv4 addresses."
  }

  validation {
    condition     = length(var.controlplanes) >= 1
    error_message = "At least one controlplane node must be defined."
  }
}

variable "talos_certs" {
  description = "Talos client certificates (base64 or PEM). Must match Talos API credentials."
  type = object({
    ca   = string
    cert = string
    key  = string
  })

  validation {
    condition = alltrue([
      var.talos_certs.ca != "",
      var.talos_certs.cert != "",
      var.talos_certs.key != ""
    ])
    error_message = "All certificate fields must be non-empty."
  }
}

variable "controlplane_yaml_path" {
  type        = string
  description = "Path to the global controlplane.yaml generated by talosctl gen config"

  validation {
    condition     = can(regex("\\.ya?ml$", var.controlplane_yaml_path))
    error_message = "Controlplane YAML path must end with .yaml or .yml"
  }
}
